apiVersion: v1
kind: ConfigMap
metadata:
  name: django.config
data:
  SQL_ROOT_PASSWORD: "Start123"
  SQL_USER: "moviesusr"
  SQL_PASSWORD: "moviespass"
  SQL_DATABASE: "movies"
  SQL_HOST: "mysql"
  SQL_ENGINE: "django.db.backends.mysql"
  SQL_PORT: "3306"
  MONGO_INITDB_ROOT_USERNAME: "root"
  MONGO_INITDB_ROOT_PASSWORD: "Start123"
  MONGO_INITDB_DATABASE: "init_db"
  MONGO_DB_HOST: "mongodb"
  MONGO_DB_PORT: "27017"
